### ISSUE TITLE
Issue with Atiro Login when 2FA is Enabled

### ISSUE THREAD

**Issue by 2745518585** [Sukwants/Atiro#7]
**Issue Description:**

**Operating System:** Windows 11 Home Chinese Insider Preview

**GCC Version:** g++.exe (x86_64-win32-seh-rev1, Built by MinGW-Builds project) 13.1.0

**Node.js Version:** 18.12.1

**Atiro Version:** 1.0.0

**Problem Description:**

When attempting to log in to Atiro, if my account has 2FA (Two-Factor Authentication) enabled, I encounter the following issue:

- error message: 
```shell
Checking login status...
Please continue in the browser...
[Error] Login failed.
```

**Comment by 2745518585** [comment]
莫鸽了，快修

**Comment by 2745518585** [comment]
师傅修一哈咩

**Comment by 2745518585** [comment]
师傅修一哈咩

**Comment by Sukwants** [comment]
won't fix

**Comment by Sukwants** [comment]
won't fix

**Comment by 2745518585** [comment]
哈麻皮

**Comment by 2745518585** [comment]
@2745518585 Fix it, as quickly as possible.

**Comment by Sukwants** [comment]
fixed

**Comment by Sukwants** [comment]
@2745518585 remember to update the version number

**Comment by 2745518585** [comment]
#9

**Comment by Sukwants** [comment]
thx
